### ISSUE TITLE
Explore automation of output dependent appendix inclusion

### ISSUE THREAD

**Issue by crsh** [crsh/papaja#168]
Currently the inclusion of appendices involves some customization that is dependent on the output format and somewhat clumsy.

For PDF we need

~~~yaml
output            :
  papaja::apa6_pdf:
    includes:
      after_body: appendix.tex
~~~

and

~~~r
render_appendix("appendix.Rmd")
~~~

For Word we need

~~~markdown
# References

<div id = "references"></div>

```{r child = "appendix.Rmd"}
```
~~~

Both can be combined by using if-switches depending on `knitr::opts_knit$get("rmarkdown.pandoc.to")` but requires some extra LaTeX code and that's a lot to digest for new users.

I would suggest trying to add a new YAML option `appendix` that takes as input the location of a R Markdown file and does all of the above processing according to the output format.

**Comment by crsh** [comment]
Okay, this may be more difficult than I thought. As far as I can tell it's currently not possible to add R code (that's also executed, such as `render_appendix()`) without modifying the original input document---and that's potentially dangerous. So I'm not sure how to best handle this.

**Comment by jvcasillas** [comment]
I am trying to use this approach to include an appendix in my manuscript but I am getting the following error: 

```
pandoc: ./includes/sections/appendix.md: openBinaryFile: does not exist (No such file or directory)
```

My front matter looks like this: 

```
output            :
  papaja::apa6_pdf:
    includes:
      after_body: ./includes/sections/appendix.tex
```

And I include the following r chunk at the end of the main .Rmd file: 

```
    ```{r, 'generate-appendix', eval=TRUE}
    render_appendix("./includes/sections/appendix.Rmd")
    ```
```

Any ideas as to why I am getting this error?

**Comment by crsh** [comment]
Hi Joseph, indeed, the problem seems to be that the appendix is located in a subdirectory. I'll take a closer look and try to fix this as soon as possible.

**Comment by crsh** [comment]
I just pushed a commit to the development branch (`devtools::install_github("crsh/papaja@devel")`) that should fix this problem.

**Comment by jvcasillas** [comment]
Hi @crsh . Thanks for taking a look at this. It still doesn't seem to work for me. I made a test document using the papaja template. The end of my front matter looks like this: 

```
documentclass     : "apa6"
classoption       : "man"
output            :
  papaja::apa6_pdf:
    includes:
      after_body: "./includes/sections/appendix.tex"
---
```

The relevant part of the main .Rmd document looks like this: 

```
    # References
    ```{r create_r-references}
    r_refs(file = "r-references.bib")
    render_appendix("./includes/sections/appendix.Rmd")
    ```
```

And my `appendix.Rmd` file has trivial text: 

```
# THis is a test

THis is my appendix. 
```

This is the error I get: 

```
label: create_r-references
pandoc-citeproc: Could not find r-references.bib
pandoc: Error running filter /usr/local/bin/pandoc-citeproc
Quitting from lines 83-85 (Untitled.Rmd) 
Error: pandoc document conversion failed with error 83
```

If I put the appendix file in the root folder and update the paths it works fine.

**Comment by crsh** [comment]
Hi Joseph, sorry for the delay. I just pushed a commit to the development branch (devtools::install_github("crsh/papaja@devel")). Would you mind trying it out and letting me know if this fixes your problem?

**Comment by crsh** [comment]
You should now also be able to simply include the path to the appendix file in the YAML front matter and let `papaja` handle the rest:

~~~yaml
appendix: "./includes/sections/appendix.Rmd"
~~~

You can also include multiple files for separate appendices:

~~~yaml
appendix:
  - "./includes/sections/appendix_a.Rmd"
  - "./includes/sections/appendix_b.Rmd"
~~~

**Comment by jvcasillas** [comment]
This looks great! Great job and thanks for your hard work. It seems to be working quite well, but there is one issue still. I am getting "Appendix A showing up at the top of the reference section. 

This is the end of my .Rmd file: 

<img width="837" alt="rmd" src="https://user-images.githubusercontent.com/1747068/42899950-98b4e446-8a95-11e8-986e-03174de0cdfb.png">

And this is the output in the pdf: 

<img width="1161" alt="screen shot 2018-07-18 at 14 18 18" src="https://user-images.githubusercontent.com/1747068/42899962-a32cc31c-8a95-11e8-9d70-3bd4ad157e25.png">

The appendix appears as it should: 

<img width="1185" alt="screen shot 2018-07-18 at 14 20 22" src="https://user-images.githubusercontent.com/1747068/42899997-bac3ba08-8a95-11e8-85a8-a2e18c6e38ee.png">

**Comment by crsh** [comment]
Ah, good catch! This was an unintended side-effect of the implementation for Word documents. My last commit should fix this.

**Comment by crsh** [comment]
Great, thanks so much for following up on this, Joseph. I think you are right and this is simply that I have not implemented support for multiple bibliography files in `render_appendix()`. I'll look into it the next chance i get.

As an aside, if you want to let BibLaTeX handle the citations, there is a "R Markdown-way" to do this. See [here](https://crsh.github.io/papaja_man/tips-and-tricks.html#author-name-disambiguation). I will add a section on this somewhere more visible in the manual.

**Comment by crsh** [comment]
I pushed another commit just now that should enable multiple bibliography files. Note, that currently every Appendix will have its own reference section unless you use a LaTeX citation package.

Note to self: To fix this I'll probably have to switch to `biblatex` by default for PDF documents. I think that change should be fine, but it'll require changing the preprocessor to include a default title for the reference section as YAML parameter for `pandoc-citeproc`. This may also be a way to get rid of the LaTeX group at the end of the template.

**Comment by jvcasillas** [comment]
That worked great! They only issue remaining that I see is the hanging indentation in the references (with or without markdown citations).  Thank you and great job. Very much appreciated.

**Comment by crsh** [comment]
Thanks for sticking with me on this. Just to clarify: If you use `biblatex` to render citations the hanging indentation is not working? For me it das work and also collects all reference in the general reference section. When I use (default) `pandoc-citeproc` for citations, I get a separate reference section in each appendix. To get hanging indentation in this case you need to add the following to your appendices:

~~~latex
\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
~~~

Are you still seeing what you reported in your [earlier post](https://github.com/crsh/papaja/issues/168#issuecomment-406032500) even with  `biblatex`?

**Comment by jvcasillas** [comment]
Sorry for not being more clear. When I use `pandoc-citeproc` for citations I do not get hanging indentations in the main reference section (I have not tried including citations in individual appendices) and I do have the `\begingroup` / `\endgroup` code at the end. 

Front matter: 

<img width="902" alt="screen shot 2018-07-20 at 11 54 06" src="https://user-images.githubusercontent.com/1747068/43012188-b6bff12c-8c13-11e8-9277-f4ce36f859e9.png">

End of Rmd doc: 

<img width="903" alt="screen shot 2018-07-20 at 11 54 18" src="https://user-images.githubusercontent.com/1747068/43012230-daf80188-8c13-11e8-894d-d750cb03c6ae.png">

Main reference section output: 

<img width="1202" alt="screen shot 2018-07-20 at 11 54 25" src="https://user-images.githubusercontent.com/1747068/43012249-e418c266-8c13-11e8-8bf0-e241292886de.png">



When I use `biblatex` citations I do get the appropriate hanging indentation.

**Comment by crsh** [comment]
Thanks for the detailed description. I'm having trouble reproducing this issue (if you find the time, it would certainly be helpful if you could provide a minimal reproducible example). Do you get hanging indentation without the appendices?

**Comment by jvcasillas** [comment]
Not a problem. Try this: 
[papaja_appendix_test.zip](https://github.com/crsh/papaja/files/2214604/papaja_appendix_test.zip)

**Comment by crsh** [comment]
Okay, I see what's causing the problem. In your TeX-file the bibliography is not inserted at the position of the refs-div. However, this seems to be related to your set up, because when I knit the document it works. What version of RStudio and pandoc are you using?

**Comment by jvcasillas** [comment]
Interesting. I moved `# References` around and got the same behavior. I then realized that I last knit the .Rmd from sublimetext and not from RStudio. When I knit from RStudio everything comes out perfect. I wonder if my sublime text is using an older version of pandoc. Anyway, I think this is solved. Thank you for your time and effort.

**Comment by crsh** [comment]
Okay, great. If you can execute R code from Sublimetext, you could try to run `rmarkdown::pandoc_version()` to compare the pandoc version with the one used by RStudio.

**Comment by SCgeeker** [comment]
Hi @crsh @jvcasillas 
I thank your great work satisfied my requirement. During my writing I found the latest papaja could pass the multi-byte character (e.g., é) when I have only one Rmd to be complied. However, the process was halted when I had several files to be compiled and the main Rmd had this sort of characters. Wish my experience will help you improve papaja.

**Comment by crsh** [comment]
Hi @SCgeeker, thanks for reaching out. Could you provide a minimal example of the main Rmd so I can try to reproduce (and subsequently fix) your problem?

**Comment by SCgeeker** [comment]
Hi @crsh,  here is one sample like the case.
[multibyte_sample.zip](https://github.com/crsh/papaja/files/2764170/multibyte_sample.zip)

**Comment by crsh** [comment]
Thanks. Rendering the document works as expected on my end. Are you working on a Windows machine? Have you tried the latest development version of `papaja` (`devtools::install_github("crsh/papaja@devel")`)?

**Comment by SCgeeker** [comment]
Sorry for late response. The problem was the same for the latest development version.
