### ISSUE TITLE
Longtable in apa_table or papaja

### ISSUE THREAD

**Issue by tormodb** [crsh/papaja#194]
I see several references to longtable in the code for apa_table, but I am not getting it to work by using longtable = TRUE as an option (and this is not documented in the function). Does papaja support longtable? 

I am not able to get longtables to "float" to the end when I produce the table using kable and kableExtra.

**Comment by crsh** [comment]
Hi, sorry for the late reply. `apa_table()` does support long tables via the `longtable` option as noted in the documentation. I'm not sure why this is not working for you. Could you provide a minimal reproducible example?

Regarding the use of `kable` and `kableExtra`: The problem is that the LaTeX `endfloat` package needs to know which LaTeX environments to float to the end. It is possible that the tables produced by the other packages are not recognized as such by `endfloat`. You can add the following to the document preamble (e.g., as `header-include` in R Markdown) to declare the environment `foo` as floating at the end:

~~~latex
\DeclareDelayedFloatFlavor{foo}{table}
~~~

See what the environments produced by `kable` and `kableExtra` are and substitute them for `foo` and it should work.

**Comment by tormodb** [comment]
So sorry about this, it was a mistake by me by leaving an "endnote.cfg" file in the root folder from a previous attempt at following the instructions from APA6 latex package to get longtable to work.

**Comment by crsh** [comment]
No, problem. I glad you found the problem. :+1:

**Comment by vrouco** [comment]
I have the same problem. knitr::kable with longtable=T prevents the table from being printed at the end of the document, in a rmarkdown with a papaja_pdf template.
I do not have any file with the extension .cfg in the root folder....

**Comment by crsh** [comment]
Hi, have you tried either using `apa_table()` or declaring the `longtable` LaTeX environment as delayed float (see my first response)?

**Comment by vrouco** [comment]
Yes I've tried. It seems that apa_table() does not work with kableExtra. Here is a small reproducible example

```
---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

author_note: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  Enter abstract here. Each new line herein must be indented, like this line.
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes
mask              : no

class             : "man"
output            : papaja::apa6_pdf

header-include:
    - \DeclareDelayedFloatFlavor{foo}{table}
---

```{r load_packages, include = FALSE}
library("papaja")
library(tidyverse)
library(knitr)
library(kableExtra)
```

```{r analysis_preferences}
# Seed for random number generation
set.seed(42)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. 

## Participants


```{r}

table1 <- tibble(first=rep(letters,3),
                 second = rnorm(78,10,2))


kable(table1, "latex", align = "l", booktabs = T, linesep="", caption = "A very long table", longtable=T) %>% 
  column_spec(1, width = "5em", bold = F, italic = F) %>%
  kable_styling(font_size = 7) %>% 
  column_spec(2, width = "8em", bold = F, italic = F) %>% 
  kable_styling(latex_options = "repeat_header")
```

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
```

**Comment by crsh** [comment]
Thanks, that was helpful. Try the development snapshot, which should fix this (`devtools::install_github("crsh/papaja@devel")`).

**Comment by vrouco** [comment]
I've installed the new version and still fails, both the minimal reproducible example and my rmarkdown file. This is the error:

! Missing \endcsname inserted.
<to be read again> 
                   \def 
l.128 ...5em}>{\raggedright\arraybackslash}p{8em}}

Error: Failed to compile trash.tex. See trash.log for more info.

**Comment by crsh** [comment]
What `pandoc` version are you using (`rmarkdown:::pandoc_version()`?

**Comment by vrouco** [comment]
2.2.1

**Comment by crsh** [comment]
Okay, I suspect this is a the same problem as https://github.com/crsh/papaja/issues/227 and was introduced with this `pandoc` version. I'll try to address this as soon as possible.

**Comment by vrouco** [comment]
OK thank you. And congrats for this amazing package!

**Comment by crsh** [comment]
Hi Víctor, I pushed a fix for this problem last night (https://github.com/crsh/papaja/issues/227#issuecomment-403965514). Could you try and see whether this resolves your problem (`devtools::install_github("crsh/papaja@devel")`)?

**Comment by crsh** [comment]
Thanks for the feedback, Víctor. The problem you are experiencing is related to the font size adjustment. The generated LaTeX code wraps the table environment in a group and the `\endgroup` command is not on a new line. In short, this seems to be a "bug" in `kableExtra` (paging @haozhu233):

`kableExtra` generates

~~~latex
\end{longtable}\endgroup{}
~~~

but `endfloat` requires

~~~latex
\end{longtable}
\endgroup{}
~~~
.

**Comment by haozhu233** [comment]
@vrouco @crsh Fixed now. I will update the CRAN ver in a few days. :)
