### ISSUE TITLE
Broken captions for tables on Word documents

### ISSUE THREAD

**Issue by tkerwin** [crsh/papaja#556]
In docx file output from quarto, tables created with `apa_table` are prefixed with

```
(#tab:unnamed-chunk-8)
**
```
-- where "8" is whatever the chunk number is.

Adding a caption field gets rid of the `**` but the erroneous table cross-reference code is still there.

I see there is a pull request from the `word-fixes` branch that looks like it could fix the issue, but it is not in the released version. Right now the released version is unusable for professional document output without editing the document after generation.

**Comment by crsh** [comment]
Hi Thomas, I just merged the branch. Could you try installing from the `main` branch and let me know if this fixes the problem for you?

**Comment by tkerwin** [comment]
This fixes a problem, but does not solve it completely for me. The fixes you merged in make the table work properly when using RMarkdown + Bookdown. However, it doesn't work for Quarto documents.

It looks like the problem is that Bookdown wants `Table: (\#tab:table-name) Caption`, but Quarto wants `: Caption {#tbl-table-name}`  (or a table label and caption metadata in the block).

I've tried to find out how to detect if the block is being parsed with RMarkdown or Quarto but I'm not sure if there is an easy way. My suggestion would be to have a configuration flag somewhere in papaja to tell the library if you want Bookdown style output or Quarto style output.

**Comment by scsphd** [comment]
I am having the same problem with an html document. My code in a chunk called ALS:
ordinal <- lapply(ord_vars, ord_table) # custom function to create the descriptives tables I want, across a list of ordinal variables
for (i in 1:length(ord_vars)) {
                              cat(
                              papaja::apa_table(ordinal[[i]],
                                                label = NA,
                                                caption = paste("Descriptives for", ord_vars[i])),
                                                "\n\n" 
                              )}

The caption is printed as: 

(#tab:ALS) Descriptives for ALSlower

I've tried doing some things that people report have interfered with reference labels, but the problem persists. 

Thanks!

**Comment by crsh** [comment]
Hi there, can you try using the document format `bookdown::html_document2` to see if this fixes the issue? If it does not, can you share a minimal reproducible example? Also, could you try using different labels for each table?

**Comment by scsphd** [comment]
bookdown::html_document2 did the trick. Thank you!

________________________________
